manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
     
      revision: a23aa009d7a07d67fe5609caca7372e16610f238
      import: app/west.yml
  self:
    path: config
