manifest:
  remotes:
    - name: myzmk
      url-base: https://github.com/tibiboard
  projects:
    - name: zmk
      remote: myzmk
      revision: mykbd=1.2
      import: app/west.yml
  self:
    path: config
